tasks:
  - name: Install Jupyter Notebook
    command: |
      pip install jupyter

  - name: Configure Jupyter Notebook server
    command: |
      python -m notebook --generate-config
      sed -i 's/# c.ServerApp.allow_remote_access = False/c.ServerApp.allow_remote_access = True/g' /home/gitpod/.jupyter/jupyter_notebook_config.py
      sed -i "s/# c.ServerApp.allow_origin = ''/c.ServerApp.allow_origin = '*'/g" /home/gitpod/.jupyter/jupyter_notebook_config.py

  - name: Install R
    init: |
      sudo curl -L https://rig.r-pkg.org/deb/rig.gpg -o /etc/apt/trusted.gpg.d/rig.gpg
      sudo sh -c 'echo "deb http://rig.r-pkg.org/deb rig main" > /etc/apt/sources.list.d/rig.list'
      sudo apt update
    command: |
      sudo apt install r-rig
